//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Demo/InputActions/Master.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Master : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Master()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Master"",
    ""maps"": [
        {
            ""name"": ""PlayerInputXbox"",
            ""id"": ""bd8d9707-fd15-41e0-ab3b-30a3252e035f"",
            ""actions"": [
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""bc5849d0-65d5-46cd-ae50-e8e723f8d4e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e24f98d3-5364-40eb-aa0b-2b57cd50e583"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwordAttack"",
                    ""type"": ""Button"",
                    ""id"": ""e388f6aa-22b1-4214-9b3e-9aa37a7ffb79"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialAttack"",
                    ""type"": ""Button"",
                    ""id"": ""ba1d9bc3-de98-4ac0-86b6-17d59e6cd2a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""09ce7278-e3d7-494d-a17a-6292ac2c12e4"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Axis"",
                    ""id"": ""3499820c-7e69-4a10-b338-73350bc45fbb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2,StickDeadzone(min=0.2)"",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""550686b7-c3dc-48b3-adc2-9e9b1e38d1fd"",
                    ""path"": ""<XInputController>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""2eb023fd-cc52-4e1d-a6e4-bd3874b1076c"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""1ac7fc2e-ac54-4b97-8fe9-6364e1d9ded6"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""76008c0e-73fb-4b85-a29c-4637b30f90dd"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""033dc06a-a943-4c5a-91b3-9c15a2ed4861"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""SwordAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8b85916-8c45-446a-ae52-9545b3fcec2e"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": ""SlowTap(duration=2,pressPoint=1)"",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""SpecialAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerInputKeyboard"",
            ""id"": ""a14928ab-4651-474f-be85-768e13881977"",
            ""actions"": [
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""4f06563e-1ec4-4019-960b-8619422f6fcb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f14e5fa1-fa91-4f85-82b6-146e99d7c870"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwordAttack"",
                    ""type"": ""Button"",
                    ""id"": ""1db44ed3-2b36-487c-983a-79b37fa0e297"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialAttack"",
                    ""type"": ""Button"",
                    ""id"": ""c44da700-73ec-46c9-a6b2-4309b4b32aba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b1201c60-0abd-475a-8dcf-29c3f54c9379"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Axis"",
                    ""id"": ""ceb36622-dd0e-4721-ab56-3966e67ff6e9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2,StickDeadzone(min=0.2)"",
                    ""groups"": ""Xbox"",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""015b67aa-829f-414b-8c4c-1c5f9b6f8980"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""9ae67c1e-86e9-4c13-ac0f-083cf70dc017"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""37eae724-0b7f-472f-8ff8-1f40433aeed3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""815da659-a213-47fb-9aa8-b6037d111488"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""595a916b-5808-409d-bcc9-c654d2075b53"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SwordAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ac80143-9ac4-4695-93ca-f6c2cdc5e6b9"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""SlowTap(duration=2,pressPoint=1)"",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SpecialAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SaveGame"",
            ""id"": ""56d83399-fafd-4f60-a9d2-0b6beb881319"",
            ""actions"": [
                {
                    ""name"": ""Create"",
                    ""type"": ""Button"",
                    ""id"": ""261f5931-a50d-4bbf-927b-854619b8c370"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Save"",
                    ""type"": ""Button"",
                    ""id"": ""7303a9ad-fe30-4ff0-9c13-007923b59207"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Load"",
                    ""type"": ""Button"",
                    ""id"": ""b8a035b8-372d-4236-972f-5de58253552e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NewGame"",
                    ""type"": ""Button"",
                    ""id"": ""f8f89038-cdb1-4de1-96ef-11a87865d131"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse"",
                    ""type"": ""Button"",
                    ""id"": ""80399756-7400-4637-b376-b7ba3e5dd4c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""d6369135-6567-4ea5-84eb-60ea2bf4557b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6ac0f5df-feaa-4688-bc16-4e11a36e3b74"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Create"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""737c740f-416f-4f96-a9b2-765ac5fc1afe"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95b13924-fdca-403a-bec9-857bebd9b27c"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Load"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aaebc2db-fd00-4176-b3d9-44aea41bf7cd"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NewGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ff799ed-c6b3-489d-86c8-a02aab92368d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""102d59d0-aa47-47b1-8691-7b8155f99e6c"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Xbox"",
            ""bindingGroup"": ""Xbox"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerInputXbox
        m_PlayerInputXbox = asset.FindActionMap("PlayerInputXbox", throwIfNotFound: true);
        m_PlayerInputXbox_Dash = m_PlayerInputXbox.FindAction("Dash", throwIfNotFound: true);
        m_PlayerInputXbox_Movement = m_PlayerInputXbox.FindAction("Movement", throwIfNotFound: true);
        m_PlayerInputXbox_SwordAttack = m_PlayerInputXbox.FindAction("SwordAttack", throwIfNotFound: true);
        m_PlayerInputXbox_SpecialAttack = m_PlayerInputXbox.FindAction("SpecialAttack", throwIfNotFound: true);
        // PlayerInputKeyboard
        m_PlayerInputKeyboard = asset.FindActionMap("PlayerInputKeyboard", throwIfNotFound: true);
        m_PlayerInputKeyboard_Dash = m_PlayerInputKeyboard.FindAction("Dash", throwIfNotFound: true);
        m_PlayerInputKeyboard_Movement = m_PlayerInputKeyboard.FindAction("Movement", throwIfNotFound: true);
        m_PlayerInputKeyboard_SwordAttack = m_PlayerInputKeyboard.FindAction("SwordAttack", throwIfNotFound: true);
        m_PlayerInputKeyboard_SpecialAttack = m_PlayerInputKeyboard.FindAction("SpecialAttack", throwIfNotFound: true);
        // SaveGame
        m_SaveGame = asset.FindActionMap("SaveGame", throwIfNotFound: true);
        m_SaveGame_Create = m_SaveGame.FindAction("Create", throwIfNotFound: true);
        m_SaveGame_Save = m_SaveGame.FindAction("Save", throwIfNotFound: true);
        m_SaveGame_Load = m_SaveGame.FindAction("Load", throwIfNotFound: true);
        m_SaveGame_NewGame = m_SaveGame.FindAction("NewGame", throwIfNotFound: true);
        m_SaveGame_Mouse = m_SaveGame.FindAction("Mouse", throwIfNotFound: true);
        m_SaveGame_MousePosition = m_SaveGame.FindAction("MousePosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInputXbox
    private readonly InputActionMap m_PlayerInputXbox;
    private IPlayerInputXboxActions m_PlayerInputXboxActionsCallbackInterface;
    private readonly InputAction m_PlayerInputXbox_Dash;
    private readonly InputAction m_PlayerInputXbox_Movement;
    private readonly InputAction m_PlayerInputXbox_SwordAttack;
    private readonly InputAction m_PlayerInputXbox_SpecialAttack;
    public struct PlayerInputXboxActions
    {
        private @Master m_Wrapper;
        public PlayerInputXboxActions(@Master wrapper) { m_Wrapper = wrapper; }
        public InputAction @Dash => m_Wrapper.m_PlayerInputXbox_Dash;
        public InputAction @Movement => m_Wrapper.m_PlayerInputXbox_Movement;
        public InputAction @SwordAttack => m_Wrapper.m_PlayerInputXbox_SwordAttack;
        public InputAction @SpecialAttack => m_Wrapper.m_PlayerInputXbox_SpecialAttack;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInputXbox; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputXboxActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerInputXboxActions instance)
        {
            if (m_Wrapper.m_PlayerInputXboxActionsCallbackInterface != null)
            {
                @Dash.started -= m_Wrapper.m_PlayerInputXboxActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_PlayerInputXboxActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_PlayerInputXboxActionsCallbackInterface.OnDash;
                @Movement.started -= m_Wrapper.m_PlayerInputXboxActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerInputXboxActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerInputXboxActionsCallbackInterface.OnMovement;
                @SwordAttack.started -= m_Wrapper.m_PlayerInputXboxActionsCallbackInterface.OnSwordAttack;
                @SwordAttack.performed -= m_Wrapper.m_PlayerInputXboxActionsCallbackInterface.OnSwordAttack;
                @SwordAttack.canceled -= m_Wrapper.m_PlayerInputXboxActionsCallbackInterface.OnSwordAttack;
                @SpecialAttack.started -= m_Wrapper.m_PlayerInputXboxActionsCallbackInterface.OnSpecialAttack;
                @SpecialAttack.performed -= m_Wrapper.m_PlayerInputXboxActionsCallbackInterface.OnSpecialAttack;
                @SpecialAttack.canceled -= m_Wrapper.m_PlayerInputXboxActionsCallbackInterface.OnSpecialAttack;
            }
            m_Wrapper.m_PlayerInputXboxActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @SwordAttack.started += instance.OnSwordAttack;
                @SwordAttack.performed += instance.OnSwordAttack;
                @SwordAttack.canceled += instance.OnSwordAttack;
                @SpecialAttack.started += instance.OnSpecialAttack;
                @SpecialAttack.performed += instance.OnSpecialAttack;
                @SpecialAttack.canceled += instance.OnSpecialAttack;
            }
        }
    }
    public PlayerInputXboxActions @PlayerInputXbox => new PlayerInputXboxActions(this);

    // PlayerInputKeyboard
    private readonly InputActionMap m_PlayerInputKeyboard;
    private IPlayerInputKeyboardActions m_PlayerInputKeyboardActionsCallbackInterface;
    private readonly InputAction m_PlayerInputKeyboard_Dash;
    private readonly InputAction m_PlayerInputKeyboard_Movement;
    private readonly InputAction m_PlayerInputKeyboard_SwordAttack;
    private readonly InputAction m_PlayerInputKeyboard_SpecialAttack;
    public struct PlayerInputKeyboardActions
    {
        private @Master m_Wrapper;
        public PlayerInputKeyboardActions(@Master wrapper) { m_Wrapper = wrapper; }
        public InputAction @Dash => m_Wrapper.m_PlayerInputKeyboard_Dash;
        public InputAction @Movement => m_Wrapper.m_PlayerInputKeyboard_Movement;
        public InputAction @SwordAttack => m_Wrapper.m_PlayerInputKeyboard_SwordAttack;
        public InputAction @SpecialAttack => m_Wrapper.m_PlayerInputKeyboard_SpecialAttack;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInputKeyboard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputKeyboardActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerInputKeyboardActions instance)
        {
            if (m_Wrapper.m_PlayerInputKeyboardActionsCallbackInterface != null)
            {
                @Dash.started -= m_Wrapper.m_PlayerInputKeyboardActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_PlayerInputKeyboardActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_PlayerInputKeyboardActionsCallbackInterface.OnDash;
                @Movement.started -= m_Wrapper.m_PlayerInputKeyboardActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerInputKeyboardActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerInputKeyboardActionsCallbackInterface.OnMovement;
                @SwordAttack.started -= m_Wrapper.m_PlayerInputKeyboardActionsCallbackInterface.OnSwordAttack;
                @SwordAttack.performed -= m_Wrapper.m_PlayerInputKeyboardActionsCallbackInterface.OnSwordAttack;
                @SwordAttack.canceled -= m_Wrapper.m_PlayerInputKeyboardActionsCallbackInterface.OnSwordAttack;
                @SpecialAttack.started -= m_Wrapper.m_PlayerInputKeyboardActionsCallbackInterface.OnSpecialAttack;
                @SpecialAttack.performed -= m_Wrapper.m_PlayerInputKeyboardActionsCallbackInterface.OnSpecialAttack;
                @SpecialAttack.canceled -= m_Wrapper.m_PlayerInputKeyboardActionsCallbackInterface.OnSpecialAttack;
            }
            m_Wrapper.m_PlayerInputKeyboardActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @SwordAttack.started += instance.OnSwordAttack;
                @SwordAttack.performed += instance.OnSwordAttack;
                @SwordAttack.canceled += instance.OnSwordAttack;
                @SpecialAttack.started += instance.OnSpecialAttack;
                @SpecialAttack.performed += instance.OnSpecialAttack;
                @SpecialAttack.canceled += instance.OnSpecialAttack;
            }
        }
    }
    public PlayerInputKeyboardActions @PlayerInputKeyboard => new PlayerInputKeyboardActions(this);

    // SaveGame
    private readonly InputActionMap m_SaveGame;
    private ISaveGameActions m_SaveGameActionsCallbackInterface;
    private readonly InputAction m_SaveGame_Create;
    private readonly InputAction m_SaveGame_Save;
    private readonly InputAction m_SaveGame_Load;
    private readonly InputAction m_SaveGame_NewGame;
    private readonly InputAction m_SaveGame_Mouse;
    private readonly InputAction m_SaveGame_MousePosition;
    public struct SaveGameActions
    {
        private @Master m_Wrapper;
        public SaveGameActions(@Master wrapper) { m_Wrapper = wrapper; }
        public InputAction @Create => m_Wrapper.m_SaveGame_Create;
        public InputAction @Save => m_Wrapper.m_SaveGame_Save;
        public InputAction @Load => m_Wrapper.m_SaveGame_Load;
        public InputAction @NewGame => m_Wrapper.m_SaveGame_NewGame;
        public InputAction @Mouse => m_Wrapper.m_SaveGame_Mouse;
        public InputAction @MousePosition => m_Wrapper.m_SaveGame_MousePosition;
        public InputActionMap Get() { return m_Wrapper.m_SaveGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SaveGameActions set) { return set.Get(); }
        public void SetCallbacks(ISaveGameActions instance)
        {
            if (m_Wrapper.m_SaveGameActionsCallbackInterface != null)
            {
                @Create.started -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnCreate;
                @Create.performed -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnCreate;
                @Create.canceled -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnCreate;
                @Save.started -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnSave;
                @Save.performed -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnSave;
                @Save.canceled -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnSave;
                @Load.started -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnLoad;
                @Load.performed -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnLoad;
                @Load.canceled -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnLoad;
                @NewGame.started -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnNewGame;
                @NewGame.performed -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnNewGame;
                @NewGame.canceled -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnNewGame;
                @Mouse.started -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnMouse;
                @Mouse.performed -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnMouse;
                @Mouse.canceled -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnMouse;
                @MousePosition.started -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_SaveGameActionsCallbackInterface.OnMousePosition;
            }
            m_Wrapper.m_SaveGameActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Create.started += instance.OnCreate;
                @Create.performed += instance.OnCreate;
                @Create.canceled += instance.OnCreate;
                @Save.started += instance.OnSave;
                @Save.performed += instance.OnSave;
                @Save.canceled += instance.OnSave;
                @Load.started += instance.OnLoad;
                @Load.performed += instance.OnLoad;
                @Load.canceled += instance.OnLoad;
                @NewGame.started += instance.OnNewGame;
                @NewGame.performed += instance.OnNewGame;
                @NewGame.canceled += instance.OnNewGame;
                @Mouse.started += instance.OnMouse;
                @Mouse.performed += instance.OnMouse;
                @Mouse.canceled += instance.OnMouse;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
            }
        }
    }
    public SaveGameActions @SaveGame => new SaveGameActions(this);
    private int m_XboxSchemeIndex = -1;
    public InputControlScheme XboxScheme
    {
        get
        {
            if (m_XboxSchemeIndex == -1) m_XboxSchemeIndex = asset.FindControlSchemeIndex("Xbox");
            return asset.controlSchemes[m_XboxSchemeIndex];
        }
    }
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IPlayerInputXboxActions
    {
        void OnDash(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnSwordAttack(InputAction.CallbackContext context);
        void OnSpecialAttack(InputAction.CallbackContext context);
    }
    public interface IPlayerInputKeyboardActions
    {
        void OnDash(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnSwordAttack(InputAction.CallbackContext context);
        void OnSpecialAttack(InputAction.CallbackContext context);
    }
    public interface ISaveGameActions
    {
        void OnCreate(InputAction.CallbackContext context);
        void OnSave(InputAction.CallbackContext context);
        void OnLoad(InputAction.CallbackContext context);
        void OnNewGame(InputAction.CallbackContext context);
        void OnMouse(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
    }
}
